Algoritmo "Taboada de n"
// Disciplina  : Algoritmos
// Professor(a): 1SAR ETA Ribeiro
// Descrição   :
// Autor(a)    :
// Data atual  :
var
// Seção de Declarações das variáveis 
       indice, numero, i : INTEIRO
inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    LIMPATELA
    ESCREVAL(" ")
    ESCREVA("Digite um número : ")
    LEIA(numero)


    PARA i DE 1 ATÉ 10 FAÇA
        ESCREVAL(i," X ",numero," = ",i * numero)
    FIMPARA
    
fimalgoritmo